apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aether.fullname" . }}
  labels:
    {{- include "aether.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aether.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aether.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aether.serviceAccountName" . }}
      securityContext: 
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes: 
        {{- if .Values.secretName }}
        - name: credentials
          secret:
            defaultMode: 420
            secretName: "{{ .Values.secretName }}"
        {{- end }}
        - name: config
          configMap:
            defaultMode: 420
            name: {{ include "aether.fullname" . }}
        {{- if .Values.plugins.exporters }}
        - name: exporters
          emptyDir: {}
        {{- end }}
        {{- if .Values.plugins.sources }}
        - name: sources
          emptyDir: {}
        {{- end }}
      initContainers:
      {{- if .Values.plugins.exporters }}
      - name: download-exporters
        image: "{{ .Values.plugins.image.repository }}:{{ .Values.plugins.image.tag }}"
        command:
        - sh
        - -c
        args:
        - echo Downloading Exporters;
          {{- range .Values.plugins.exporters }}
          echo Fetching "{{ .link }}";
          wget "{{ .link }}" -O /exporters/{{ .name }};
          chmod 755 /exporters/{{ .name }};
          {{- end }}
          echo Finished downloading;
        volumeMounts:
        - mountPath: /exporters
          name: exporters
      {{- end }}
      {{- if .Values.plugins.sources }}
      - name: download-sources
        image: "{{ .Values.plugins.image.repository }}:{{ .Values.plugins.image.tag }}"
        command:
        - sh
        - -c
        args:
        - echo Downloading Sources;
          {{- range .Values.plugins.exporters }}
          echo Fetching "{{ .link }}";
          wget "{{ .link }}" -O /sources/{{ .name }};
          chmod 755 /exporters/{{ .name }};
          {{- end }}
          echo Finished downloading;
        volumeMounts:
        - mountPath: /sources
          name: sources
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          - name: AETHER_CONFIG
            value: local
            {{- toYaml .Values.env | nindent 10 }}
          volumeMounts:
            - mountPath: /conf
              name: config
            {{- if .Values.secretName }}
            - name: credentials
              mountPath: /etc/secrets
            {{- end }}
            {{- if .Values.plugins.exporters }}
            - mountPath: /plugins/exporters 
              name: exporters
            {{- end }}
            {{- if .Values.plugins.sources }}
            - mountPath: /plugins/sources
              name: sources
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
