version: 0.2
ignorePaths: []
patterns: []
ignoreRegExpList: []
words:
  - aether
  - kepler
  - scaphandre
  - teads
  - rapl
  - cpuco
  - cinq
  - fargate
  - turbostat
  - runge
  - jóakim
  - kistowski
  - kounev
  - equi
  - cgroups
  - gospline
  - snippit
  - structs
  - pkgwatt
  - turbostress
  - gcloud 
  - gserviceaccount
  - configmap
  - servicemonitors
