version: '3.1'

services:

  carbon:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./:/src
      # Volume for Google Cloud Credentials
      - ~/.config/gcloud/application_default_credentials.json:/credentials/application_default_credentials.json
      # volume for AWS credentials
      - ~/.aws/credentials:/credentials/credentials

