{
 "title": "Aether Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Carbon Emissions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Emissions by Node Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gCO2eq" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (machine_type) (emissions{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Embodied Emissions",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gCO2eq" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(embodied{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heatmap of Emissions by Instance",
   "type": "heatmap",
   "gridPos": { "h": 25, "w": 8, "x": 16, "y": 1 },
   "targets": [
    { "expr": "sum by (name) (emissions{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Operational Emissions - Real Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 13 },
   "targets": [
    { "expr": "sum by (name) (emissions{})", "legendFormat": "{{name}}" }
   ]
  }
 ]
}