# Default values for aether.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: recinq/aether
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "" 

# if you want to pass secrets like credentials to aether
# this secret will be volumed under `/etc/secrets`
secretName: ""

# This is equivalent to the `local.yaml` file, and aether
# provides sane defaults for each variable, so this shouldn't
# be necessary unless you want to override the defaults.
config: {}

# some plugins need extra environment variables
# you can set them here
# example
# env:
# - name: EXAMPLE_ENV
#   value: foobar
env: []

# plugin configuration
plugins:
  # image used to download the binaries
  # requires wget
  image:
    repository: alpine
    pullPolicy: IfNotPresent
    tag: "3.15" 

  # a list of links that get plugins from
  # example:
  # exporters:
  # - link: https://example.com/example
  #   name: example
  # sources:
  # - link: https://example.com/example
  #   name: example
  exporters: []
  sources: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# The port the service listens on, by default this is 8080
# in aether, and for health checks and kubernetes resource
# configurations, this should match that value.
service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

